---
title: "Abstract"
author: Charlie PAUVERT
classoption: a4paper
fontsize: 12pt
lang: en
output:
  pdf_document:
    pandoc_args: [ "--latex-engine=/usr/bin/pdflatex" ] 
    number_section: true
header-includes:
 - \usepackage{libertine}
--- 

#Cheese ecosystems metagenomics: an exploration 

Cheese complex flora --composed of dairy micro-organisms-- is not completely and exactly known in most cheeses.
Further understandings of these ecosystems needs a better characterization of the cheese flora and a precise taxonomic identification.
Hundreds of genomes extracted from dairy products are currently available in genomics databases. 
But the key points to tackle are low abundant species and identification up to the strain level.
A tool was developed in the team to address these issues using shotgun metagenomics sequencing data.

I have focused my research around this tool for two years. 
<!-- This work can be crystallised into four axes. -->
I mostly worked on scientific improvements: deeply exploring new leads to enhance ecosystem taxonomic identification.
Notably I designed an approach taking into account the discrepancy between reference genomes and genomes from the environment.
However, it did not yields expected results despite a thorough examination of model limits. 

I have also worked on computational features improvements such as compatibility by using standard bioinformatics files.
This conversion leads to space usage and speed improvements.  
I am involved in the integration of this tool with a metadata-extended database.


<!-- (B) Integration with others tools and computational improvements: through the standardisation of output files.-->




